[package]
name = "crabgrass"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
walkdir = "2.5.0"
